### Introduction

In [2]:
import requests
response = requests.get('https://data.texas.gov/resource/naix-2893.json?location_address=2411%20GLENNA%20GOODACRE%20BLVD')
results = response.json()

In [3]:
import pandas as pd
results_df = pd.DataFrame(results)

In [4]:
top_three = results_df[0:3]

In [5]:
beer_and_liquor_df = results_df[['beer_receipts', 'liquor_receipts', 'total_receipts']].apply(pd.to_numeric)

In [6]:
beer_receipts = beer_and_liquor_df['beer_receipts'].to_numpy()

In [7]:
beer_receipts

array([114, 115, 158, 208, 378, 409, 153, 346, 504, 162, 187, 515, 442,
       103, 429, 278, 158,   0,   0, 538, 297, 590, 438, 398, 115,   0,
       129, 535, 208, 313, 407,  93, 498, 394, 308, 615, 354, 381, 175,
       251, 160, 378, 517, 337, 460, 394, 196, 211, 323, 148, 149,  88,
       204, 777, 508, 128, 244, 251, 266, 381, 115, 147, 165, 434, 516,
       256, 396, 218, 315, 235, 160, 149, 187, 559, 410, 292, 650,  86,
       530, 142, 194, 187, 205, 527, 143, 584,  92, 249, 267, 171, 472,
       385, 643, 455, 185,  97, 367, 342, 497, 527, 310, 387])

In [8]:
liquor_receipts = beer_and_liquor_df['liquor_receipts'].to_numpy()

In [9]:
liquor_receipts

array([ 76, 137, 116, 147, 631, 560, 116,  81, 261, 147, 249, 615, 787,
        69, 682,  27,  78,   0,   0, 327, 334, 815, 409, 445,  31,   0,
       183, 302, 204, 656, 761,  59, 937, 185, 144, 315, 480, 602, 175,
       297, 163, 357, 935, 167, 189, 662, 241,  78, 189, 144, 114, 121,
        95, 514, 248, 118, 178, 161, 349, 486,  76, 128, 329, 252, 319,
       213, 488, 168, 595, 251, 139, 159, 161, 275, 319, 334, 340, 133,
       288,  75,  76, 172, 380, 252, 111, 342, 151, 280, 166, 149, 167,
       482, 302, 185, 185,  78, 383, 531, 180, 234, 144, 149])

### Working with Vectors in Numpy

Let's assume that chipotle earns $.20$ in marginal profit for every dollar of liquor sold, and $.10$ of marginal profit for every dollar of beer sold.

Calculate the marginal profit for liquor for each month.

In [11]:
marginal_liquor = .2*liquor_receipts
marginal_liquor[0:5]
# array([ 15.2,  27.4,  23.2,  29.4, 126.2])

array([ 15.2,  27.4,  23.2,  29.4, 126.2])

In [13]:
marginal_beer = .1 * beer_receipts
marginal_beer[0:5]
# array([11.4, 11.5, 15.8, 20.8, 37.8])

array([11.4, 11.5, 15.8, 20.8, 37.8])

Now calculate the total marginal profit on all alcohol sales -- assume that beer and alcohol receipts are the only source of alcohol revenue.

In [15]:
total_margins = marginal_liquor + marginal_beer
total_margins[0:5]
# Please check your own work for this one

array([ 26.6,  38.9,  39. ,  50.2, 164. ])

Calculate the percentage of revenue that goes towards marginal profits each month.

In [17]:
margin_percentage = total_margins/(liquor_receipts+beer_receipts)
margin_percentage[0:3]

# array([0.14      , 0.15436508, 0.14233577])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.14      , 0.15436508, 0.14233577])

If we look at the array, there are three nan entries.

In [18]:
import numpy as np
np.argwhere(np.isnan(margin_percentage))

# array([[17],
#        [18],
#        [25]])

array([[17],
       [18],
       [25]])

In [19]:
liquor_receipts[17],beer_receipts[17] #we don't have any receipts for those months


(0, 0)

In [20]:
beer_receipts[18], liquor_receipts[18]

(0, 0)

In [22]:
beer_receipts[25], liquor_receipts[25]

(0, 0)

Why do you think that is?  Show your reasoning in code.

### Summary

Great job!  In this lesson we practiced adding and multiplying vectors in numpy.